[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@uniswap/v3-core/contracts/=lib/v3-core/contracts/',
    '@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/'
]

# Allow both 0.7.6 and 0.8.20
[profile.uniswap]
solc = "0.7.6"
src = "lib/v3-core/contracts"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@uniswap/v3-core/contracts/=lib/v3-core/contracts/',
    '@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/'
]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
