[tool.poetry]
name = "horus"
version = "0.1.0"
description = "Horus project for EthDenver2025"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10.12"
coinbase-agentkit = {version = "^0.1.4.dev202502250", allow-prereleases = true}
coinbase-agentkit-langchain = {version = "^0.1.1.dev2025022120250221202502212", allow-prereleases = true}
openai = "^1.64.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dev = "horus.main:main"
